wannier-berri/wannier-berri

- wannierberri/__kubo.py
Dear developers,
This PR implements the optimization of the optical conductivity routine.
1) The bottleneck was the einsum call, which had many arguments. As Stepan suggested, I refactored this with smaller einsum and matmul calls.
2) The evaluation of Gaussian is optimized by computing only nonzero elements. np.exp(-x) is set to 0 for x > -200.
The runtime without and with the optimizations are the following.
* No optimization (master branch, 3513555): 69.76 sec
* Optimization 1: 8.26 sec
* Optimizations 1 and 2: 5.51 sec
I checked that the symmetric and asymmetric part of the optical conductivity of Fe computed with the old and new codes are identical up to numerical errors (error ~ 1E-12).
I also deleted the "# free memory" parts in __kubo.py. If they should be kept, I will put them …
> Optimization of optical conductivity (__kubo.py)

- wannierberri/__Data_K.py
I optimized `shc_B_H` by replacing `einsum` with matrix multiplication, transposing and reshaping. This improves the performance of opt_SHCqiao calculation.
Optimization of `einsum` reduces the time taken in `shc_B_H` is from 243s to 82s. After the optimization, the bottleneck is `_R_to_k_H` inside `shc_B_H`  (~50% of total time). See details below.
I checked with bulk Pt that the calculation result does not change after optimization.
This optimization was discussed in https://github.com/stepan-tsirkin/wannier-berri/pull/22#discussion_r532286534
I tried 1) using `einsum_path` and 2) factoring out the 'k' index from the einsum call (but still using einsum inside the loop). But, both did not give any speedup.
Dear @migueldiascosta, could you (or the user, Truman Ng Yu - I could not find the …
> WIP: Optimization of einsum in shc_B_H

- tests/compare_result.py
- tests/test_smoother.py
- wannierberri/__main.py
- wannierberri/__utility.py
I reorganized the Smoother modules. The purpose is to make implementation of new Smoothers easier.
I defined an AbstractSmoother, which defines `smt`, `__call__`, and a few other methods, but not `_broaden`. Each specific Smoother inherits the AbstractSmoother and only implements its own `_broaden`. VoidSmoother is a special case in which `__call__` is also overriden.
I renamed `Smoother` to `FermiDiracSmoother` and added `GaussianSmoother`. Currently, `GaussianSmoother` is not used in the code, but later it might be possible to use it to smooth functions of frequencies, in e.g. Kubo routines. (But it needs some thinking because for frequencies, in the zero-smearing limit, we have delta functions, not step functions as for occupations.)
Also, I moved some LazyProperties to `__init__` …
> Reorganize Smoother

- .github/workflows/ci.yml
- tutorial/example.py
- wannierberri/__parallel.py
With the new Parallel class, using ray was giving error when shutting down python (can be reproduced by running example.py in tutorial). The reason is that `__del__` is called when shutting down python, but imported modules are already deleted, so python cannot run `ray.shutdown()`.
This error may be related to https://github.com/wannier-berri/wannier-berri/pull/52#issuecomment-886157263.
Here, I renamed `__del__` to `shutdown` so that it is not called when shutting down python. Users can close their Parallel object by `parallel.shutdown()`. I also added python 3.6 test.
> Ray fix for error on shutdown

- tests/compare_result.py
- tests/conftest.py
- tests/create_system.py
- tests/test_cluster.py
- tests/test_formatted.py
- tests/test_integrate.py
- tests/test_kubo.py
- wannierberri/__w90_files.py
1. Fix a bug that `mmn.data` is changed when computing `BB`. This happens when `morb` and `SHCqiao` are both true.
2. Add some comments on `parallel_ray` fixture. If in the future a `Parallel` object with a different ray setting is included in the test suite, one needs to take care to shutdown parallel object before initiating a new one.
3. Make `rootdir` and `output_dir` constant functions. Since their values are not changed, they need not be fixtures. I think same holds for the various parameters in `test_integrate.py`: they can just be constants.
The benefit is that they can be used in non-fixture functions.
> Various fixes

- wannierberri/__grid.py
- wannierberri/__main.py
* In `integrate`, `smearW` is imposed to be `None` (i.e. not used), but the default was `10`. I changed the default to `None`, and updated the warning that is printed if it is not `None`.
* Fixed typos: "qantities" -> "quantities", "%%" -> "%"
> Set smearW=None as default, fix typos

- wannierberri/__evaluate.py
- wannierberri/__main.py
Added `print_Kpoints` argument to `integrate` and `tabulate`. When set to `False`, the list of K points are not printed. The default is `True`.
I added this option because when I have many K points, the output becomes very long.
> Add option to disable printing of K points

- .github/workflows/ci.yml
As the pyFFTW issue (#114) is fixed (on the pyFFTW side), python3.9 can be safely added to CI.
Python3.6 reached its end of life (https://endoflife.date/python), so we could remove it from CI, but I just left it because it does little (or no) harm.
> Add python3.9 to CI

- wannierberri/__system.py
- wannierberri/__system_w90.py
- wannierberri/__tabulate.py
- wannierberri/__w90_files.py
To use `pytest-cov` with `multiprocessing.Pool`, one needs to explicitly write `pool.close()` and `pool.join()` after using a Pool. (See below if you want the details.) This was not the case in the code, so pytest with code coverage calculation hang, leading to timeout in CI. (I do not know why this problem did not appear until a few days ago, though...)
I added `pool.close()` and `pool.join()` to fix the problems. Also, it seems it is good practice to always call these two functions: https://stackoverflow.com/questions/20387510/proper-way-to-use-multiprocessor-pool-in-a-nested-loop.
I have one question: is the function `pool` in `__parallel.py` still needed? If we only need `pool(0)` case, then we can remove or simplify it. There is this line with `pool(npar_k)` …
> Fix CI problem related to codecov and multiprocessing

- tests/test_symmetry.py
- wannierberri/symmetry.py
Previously, if a generator for an infinite group is passed to the `symmetry.Group` constructor, it did not raise but fall into an infinite loop. I fixed the constructor to raise. Added a test.
Assumes #140 is merged
Reproducer:
```python3
import numpy as np
import wannierberri.symmetry as sym
c = np.cos(0.1)
s = np.sin(0.1)
y = sym.Group([sym.Symmetry(np.array([[1, 0, 0], [0, c, s], [0, -s, c]]))])
```
> Fix symmetry Group constructor to raise for an infinite group

- .github/install_script.sh
- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- tests/common_systems.py
- tests/test_symmetry.py
- wannierberri/__system.py
- wannierberri/symmetry.py
* Added method `System.set_structure` that sets `positions`, `atom_numbers` (Integer numbers to distinguish species), and `magnetic_moments` (optional) attributes.
* Added method `System.set_symmetry_from_structure` that uses spglib to automatically detect symmetry of the system and sets the `symgroup` attribute.
Implements the first two steps of #139.
Assumes #140, #146 are merged.
Fixes #144.
For magnetic systems, symmetries involving time reversal (e.g. `SYM.C2x * SYM.TimeReversal`) are not detected because spglib does not support such symmetries. (For non-magnetic systems, TimeReversal is added to the generator so there is no problem.)
> Automatic symmetry detection using spglib

- tests/test_kubo.py
- wannierberri/__kubo.py
Shift current is odd under inversion, but `Iodd` was set to False. Fix this bug.
> Fix wrong symmetry of opt_shiftcurrent

- setup.py
@stepan-tsirkin @Liu-Xiaoxiong @manxkim 
If I install wannierberri in a fresh environment, I get `ModuleNotFoundError: No module named 'spglib'`, and the same for `sympy`. I added them to `setup.py`.
**Since this issue blocks installation, we need to merge and release this PR before the school.**
You can test fresh installation using the following commands:
```bash
export PYTHONNOUSERSITE=True
conda create -n wbtest python=3.8.5
conda activate wbtest
pip install wannierberri
python3 -c "import wannierberri"
```
(The first line is to isolate the conda env from previously installed packages: https://stackoverflow.com/questions/35835274/how-to-reuse-global-site-packages-in-conda-env)
To install from this branch:
```bash
pip install git+https://github.com/wannier-berri/wannier-berri.git@instal …
```
> Add spglib and sympy to dependency

- tests/test_smoother.py
- wannierberri/__init__.py
- wannierberri/__old_API/__main.py
- wannierberri/smoother.py
See also https://github.com/wannier-berri/wannier-berri-org/pull/13
Also renamed function `getSmoother` to `get_smoother` to follow the python naming convention.
> Improve docstrings for smoother

- wannierberri/system/system_fplo.py
One of the used indices seems to be false, the calculated distance vector (R_vec) is in turn not an integer linear combination of the Bravais vectors. This results in an assert error in line 98.
My corrent choice (iw,jw) reproduced the correct band structure.
> Solved index issue in the FPLO Hamiltonian reading function.

- setup.py
At the moment the new `spglib-2.0,x` give errors 
```
FAILED tests/test_symmetry.py::test_symmetry_spglib_Fe - AssertionError: Symmetry group size is different
```
So far let's stick to spglib<2 . Should we set a lower bound?
@Liu-Xiaoxiong , please take a note for later to figure out what they changed and how to make it compatible
> fixed spglib<2

- wannierberri/__Kpoint.py
In class `KpointBZ`, I suggest chaing the attribute `_max` as a lazy property, since once it is calculated its value does not change. Since this attribute is calculated in every adaptive refinement iteration for all kpoints in `Klist`, caching of this attribute will make the code more efficient.
> Change the attribute KpointBZ._max into a lazy property

- tests/test_run.py
- wannierberri/calculators/dynamic.py
In class `DynamicCalculator`, if the Fermi level is far too lower (or too higher) than energy bands so that every band is unoccupied (or occupied), then `npair == 0` and the subsequent matrix calculations emit an error because the sizes of relevant arrays are zero.
This PR fixes this bug.
> Fix an edge case in DynamicCalculator

- tests/test_tetra.py
- wannierberri/__tetrahedron.py
I noticed some weird behaviour of tetrahedron method in some cases,.
Basically, the origin is that in numerics it matters in what order to perform arithmetic operations. 
The problem arises only for specific values of the energies in tetrahedron, in particular those that are close to each other. 
I fixed that for `der=0`, in future we need to check also for derivatives.
> fixed the tetrahedron method to be more accurate with der=0

- tests/test_run.py
- wannierberri/__tetrahedron.py
A small bug, but it made the result dependent on the range of Fermi levels used. 
Say, if we extend the array of Fermi levels, the result for the old Fermi levels should stay the same, but it was not the case. Now fixed. 
Also extended the Chiral test (this extension fails with old version)
> fixed a bug for tetrahedron method

- setup.py
- tests/test_aux.py
- tests/test_projections.py
- tests/test_wannierise.py
- wannierberri/symmetry/Dwann.py
- wannierberri/symmetry/orbitals.py
- wannierberri/symmetry/point_symmetry.py
- wannierberri/symmetry/projections.py
- wannierberri/symmetry/sawf.py
- wannierberri/symmetry/sawf_kirr.py
- wannierberri/symmetry/sym_wann_2.py
- wannierberri/symmetry/utility.py
- wannierberri/system/system.py
- wannierberri/system/system_R.py
- wannierberri/utility.py
- wannierberri/utils/vaspspn.py
- wannierberri/w90files/chk.py
- wannierberri/w90files/mmn.py
- wannierberri/w90files/unk.py
- wannierberri/w90files/w90data.py
- wannierberri/wannierise/wannierise.py
Fixes a series of bugs that made the SAWF inaccurate:
1) Checking explicitly the Symmetrizer_Uirr, abd excluding the blocks which do nbot symmetrize accurately (usually those are the upper block, where the nbands cuts through an irrep0
2) iteratively symmetrize+orthogonalize (until convergence is reached)
3) require irrep>=2.3.3
4) require python >=3.11
5) allow to use certain symmetries from spacegroup, in creating the pointgroup, and in symmetrize2
6) clear cached inverse after select_bands in symmetrizer
7) check_mmn, check_amn
8) self-checking the symmetrizer in Uirr
9) modified clear_cached, to NOT call the object that it was creating
> Fix bugs in SAWF
