wannier-berri/wannier-berri

wannierberri/__Data_K.py, wannierberri/__fermisea2.py, wannierberri/__integrate.py
=> update k-tensor branch

tutorial/li_bcc.py, wannierberri/__init__.py, wannierberri/__system.py, wannierberri/__system_pythtb.py
Added PythTB interface and example of lithium bcc with s orbitals, extracted from http://www.physics.rutgers.edu/~dhv/pythtb-book-examples/ptb_samples.html
=> PythTB interface and example

wannierberri/__system_pythtb.py, wannierberri/__system_tbmodels.py
Added docstrings in the interfaces including links written to be clickable
=> Added docstrings

wannierberri/__system.py, wannierberri/__system_tb.py, wannierberri/__system_tb_py.py, wannierberri/__system_w90.py
Fixed small typo: Reommended -> Recommended
=> Fix small typo

wannierberri/mmn2uHu.py
Without this, there appears a problem in making sHu and sIu when NB_out /= NB_in.
=> specify the 3rd comp. of SPN in sXu (mmn2uHu)

wannierberri/__main.py
I modified the code as what I wrote in the previous email. This is to obtain directly plottable FermiSurfer data.
=> Corrected small inconsistencies

wannierberri/__integrate.py, wannierberri/__kubo.py
The new parameters, also used in Wannier90, are added to the set of additional parameters.
There is also going to be a PR in -org.
=> shc_alpha, shc_beta, shc_gamma added

README_TESTS.rst, tests/.gitignore
=> Readme for tests

tutorial/Li_bcc_PythTB2WB.py, wannierberri/__init__.py, wannierberri/__system.py, wannierberri/__system_tb_py.py
Fix of a problem reported by Se Young Park on the mailing list.
=>  fixed a bug with low-dimensional TB models

tests/test_kubo.py, wannierberri/__system_w90.py
=> abort calculation in System_w90 if gamma point is not on the grid

.github/workflows/ci.yml, setup.py
=> required python>=3.6, added testing under 3.6 and 3.7

.github/codecov.yml
=> Make codecov ignore files in tests folder

tests/create_system.py, tests/test_integrate.py, wannierberri/__Data_K.py, wannierberri/__system.py
Changes according to review comments that were missed in #77.
=> Cleanup of wcc related changes

RELEASE_NOTES.md, wannierberri/__init__.py
commiting changes that I forgot last time
=> update for releasing v0.11.0

wannierberri/__system_w90.py
Implements the workaround as discussed in #93
Closes #93
=> Add guiding_centers argument to System_w90

tests/test_path.py, wannierberri/__path.py
Fix the k-point duplication issue mentioned in https://github.com/wannier-berri/wannier-berri/issues/99#issuecomment-987771817
Added tests
=> Remove node duplication in Path

wannierberri/__system.py, wannierberri/__tetrahedron.py
looks like the methods got duplicated after an incorrect merge of #80  . But still a mistery how it happened
=> removed duplicate methods reverseR and conj_XX_R in System()

RELEASE_NOTES.md, wannierberri/__init__.py
=> update for releasing va.b.c; git push origin release

.github/workflows/codecov.yml
To separate bugs related to codecov from bugs that aren't.
=> Split testing and coverage calculation in CI

tests/compare_result.py, tests/create_system.py, tests/test_integrate.py, tests/test_run.py, tests/test_tabulate.py, wannierberri/__result.py, wannierberri/calculators/static.py, wannierberri/models.py
* allowed the Chiral model to be left- or right-handed
* test that flipping handedness reverses berry_dipole
* test that TR flips AHC
=> more tests with chirality and TR-braking

wannierberri/system/sym_wann.py, wannierberri/system/system.py
rearrange 'qe' data back after symmetrization. 
symmetrization results are stable now.
We can run symmetrization more than once but not substantially change the result.
I change the doc as well.
=> rearrangement of 'qe' data

wannierberri/data_K.py, wannierberri/formula/covariant.py, wannierberri/system/system.py, wannierberri/system/system_ASE.py, wannierberri/system/system_fplo.py, wannierberri/system/system_phonon_qe.py, wannierberri/system/system_tb.py, wannierberri/system/system_tb_py.py, wannierberri/system/system_w90.py
now the ??_R matrices are stored in a dictionry, both in system and Data_K. This is to avoid the unclear uses of vars() and locals() . This is for internal esthetics and clearness. The behaviour of the code did not change.
=> refactoring ??_R 

tests/common_systems.py, tests/conftest.py, tests/test_run.py, wannierberri/__utility.py, wannierberri/system/__init__.py, wannierberri/system/system.py, wannierberri/system/system_sparse.py
allowed to get the most important matrix elements as a list, which frther can be imported to SystemSparse()
=>  SystemSparse

setup.py, tests/test_run.py, wannierberri/system/sym_wann.py, wannierberri/system/sym_wann_orbitals.py, wannierberri/system/system.py
some rearrangements to make code more laconic
=> rearrangements in sym_wann

wannierberri/__utility.py, wannierberri/system/sym_wann.py, wannierberri/system/system.py
np.zeros_like is very slow . See discussion [here](https://stackoverflow.com/questions/27464039/why-the-performance-difference-between-numpy-zeros-and-numpy-zeros-like)
I noticed, that it makes the `Gaussian` and `FermiDirac` functions considerably slower
=> changed all zeros_like to np.zeros

setup.py, tests/test_symmetry.py, wannierberri/symmetry.py, wannierberri/system/system.py
made use of time_reversals in spglib-2
=> compatibility with spglib>=2

tests/common_systems.py, tests/conftest.py, tests/test_run.py, tests/test_sym_wann.py
separated tests of sym_wann into one file, added a bit more tests
=> more tests of sym_wann

tests/common.py, tests/common_systems.py, tests/test_exceptions.py, wannierberri/__factors.py, wannierberri/calculators/dynamic.py, wannierberri/system/system_R.py, wannierberri/system/system_phonon_qe.py
* allowed to run certain tests without installing many packages
=> * removed imaginary part of shift current

.github/install_script.sh, setup.cfg, tests/test_sym_wann.py, wannierberri/grid/__grid.py, wannierberri/system/disentanglement.py, wannierberri/system/sym_wann.py, wannierberri/system/system.py, wannierberri/system/system_R.py, wannierberri/system/system_random.py, wannierberri/system/system_w90.py, wannierberri/system/w90_files.py
=> Docstrings

tests/common_systems.py, tests/test_run.py, tests/test_system.py, wannierberri/__utility.py, wannierberri/data_K.py, wannierberri/symmetry/sym_wann_2.py, wannierberri/system/rvectors.py, wannierberri/system/system_R.py, wannierberri/system/system_fplo.py, wannierberri/system/system_phonon_qe.py, wannierberri/system/system_random.py, wannierberri/system/system_sparse.py, wannierberri/system/system_tb.py, wannierberri/system/system_tb_py.py, wannierberri/system/system_w90.py
the order of indices for all R-space matrices is now [iR, WF1, WF2, ....]. Earlier it was [WF1 ,WF2, iR, ...]
=> Reorder xxr

tests/test_aux.py, tests/test_sym_wann.py, wannierberri/symmetry/orbitals.py, wannierberri/symmetry/sym_wann_2.py, wannierberri/system/system_R.py, wannierberri/system/system_tb_py.py, wannierberri/utility.py
there was a bug, that affected only some spacegroups (those not covered by the old tests)
=> Fixed a bug in R-space symmetrization
